name: Test

on: push

env:
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  DEPLOYER: ${{ secrets.DEPLOYER }}

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Node install
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Dependencies
      run: yarn install --forzen-lockfile

    - name: Accounts
      run: |
        echo "[ \"$DEPLOYER\" ]" > .accounts

    - name: Test
      run: yarn full_test
