name: Test

on: push

env:
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  DEPLOYER: ${{ secrets.DEPLOYER }}

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Node install
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Dependencies
      run: yarn install

    - name: Accounts
      run: |
        echo "[ \"$DEPLOYER\" ]" > .accounts

    - name: Test
      run: yarn test
